#!/bin/bash
# This is intended for use with bluetooth-connected sixad controllers.
# To be honest, this is a "quick hack" that makes up for some bugs in
# the bluetooth reset logic when a sixad-compatible controller is
# disconnected from bluetooth.

JOYSTICK=/dev/input/js0

if [ -f /etc/sixad-monitor.conf ] ; then
    . /etc/sixad-monitor.conf
fi

while : ; do
    while [ ! -f $JOYSTICK ] ; do
        sleep 2
    done

    sleep 2
    if [ ! -f $JOYSTICK ] ; then
        echo "$JOYSTICK disappeared!  Restarting bluetoothd and sixad..."
        while : ; do
            service sixad stop || continue
            service bluetooth restart || continue
            sleep 2 # give some time for the previous service to initialize
            service sixad start || continue
            break
        done
        echo "bluetoothd and sixad restarted."
    fi
done